### ISSUE TITLE
为什么出现了一对报错（纯小白）

### ISSUE THREAD

**Issue by tichen111** [KingRayCao/PKU-Annual-Eat#9]
![Uploading ca0742da-4b68-4ee7-82ce-9129d504822b.png…]()

**Comment by tichen111** [comment]
请输入开始日期(YYYY-MM-DD，默认2024-01-01): 
输入的开始日期无效，使用默认值: 2024-01-01
请输入结束日期(YYYY-MM-DD，默认2024-12-31): 
输入的结束日期无效，使用默认值: 2024-12-31
开始日期: 2024-01-01, 结束日期: 2024-12-31
Traceback (most recent call last):
  File "C:\Users\HUAWEI\PycharmProjects\PythonProject6\1.py", line 77, in <module>
    data = json.loads(response.text)["rows"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HUAWEI\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by KingRayCao** [comment]
检查一下两个值有没有填错，没有就再试几次

**Comment by KingRayCao** [comment]
可能要关闭代理

**Comment by andyhandsom6** [comment]
确实，这个报错很玄学，再`python main.py`一次就能跑通了
